In [1]:
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
import mpl_toolkits.axisartist.floating_axes as floating_axes
import mpl_toolkits.axisartist.angle_helper as angle_helper
from mpl_toolkits.axisartist.grid_finder import MaxNLocator
from matplotlib.transforms import Affine2D
from scipy.integrate import quad as quad
import sys
sys.path.insert(0, "/scratch/ierez/IGMCosmo/VoidFinder/python/")
#import voidfinder
#from voidfinder import distance
#from voidfinder.distance import z_to_comoving_dist
from astropy import constants as const
from astropy.table import Table
import scipy.integrate

import os
from astropy.io import fits
in_directory='/scratch/ierez/IGMCosmo/VoidFinder/outputs/check/'
os.chdir(in_directory)

In [2]:
deltas_filename = '/scratch/sbenzvi_lab/boss/dr16/delta_fields/deltafields_RAadded90.fits' #delta_fields
quasars_filename='/scratch/sbenzvi_lab/boss/dr16/delta_fields/quasars.fits'

In [3]:
deltas = fits.open(deltas_filename)  
deltas=Table(deltas[1].data)

In [4]:
quasars = fits.open(quasars_filename)  
quasars=Table(quasars[1].data)

In [5]:
deltas[0:5]

<Table length=5>
        ra               dec                 z                 delta        
     float64           float64            float64             float64       
----------------- ------------------ ------------------ --------------------
55.09803355164553 -1.159330826846483   3.08463316655781  -2.6700565094875603
55.09803355164553 -1.159330826846483 3.0855737963916345  -1.4396249644115322
55.09803355164553 -1.159330826846483 3.0865146428384156 -0.45740696573626016
55.09803355164553 -1.159330826846483  3.087455705948044    4.137706831117744
55.09803355164553 -1.159330826846483 3.0883969857704057    1.155314062862347

In [6]:
quasars[0:5]

<Table length=5>
         ra                 dec                z        
      float64             float64           float64     
------------------- ------------------- ----------------
 -34.90196644835447  -1.159330826846483            3.774
-34.692674572422334 -1.0531637172445856            3.446
 -34.60865459248191 -0.8345530857219153 2.75148963928223
-34.472523569472685 -0.9748963978803513            2.704
-34.444164549902894  -1.142452301903663            2.341

In [7]:
len(deltas)

4418157

In [8]:
len(quasars)

9666

In [9]:
max(deltas['ra'])

134.9965881299792

In [10]:
max(quasars['ra'])+90

134.9965881299792

In [11]:
deltas['ra']=deltas['ra']-90

In [12]:
max(deltas['dec'])

1.2497438186982022

In [13]:
max(quasars['dec'])

1.2497438186982022

In [14]:
corner_data=deltas[deltas['ra']==quasars[0]['ra']] 
min(corner_data['z'])
corner_data[corner_data['z']==min(corner_data['z'])]

<Table length=1>
        ra                dec                z                delta       
     float64            float64           float64            float64      
------------------ ------------------ ---------------- -------------------
-34.90196644835447 -1.159330826846483 3.08463316655781 -2.6700565094875603

In [15]:
#corners=Table
corners=Table(corner_data[corner_data['z']==min(corner_data['z'])][0])

In [16]:
corners

<Table length=1>
        ra                dec                z                delta       
     float64            float64           float64            float64      
------------------ ------------------ ---------------- -------------------
-34.90196644835447 -1.159330826846483 3.08463316655781 -2.6700565094875603

In [17]:
corner_data[corner_data['z']==max(corner_data['z'])][0]

<Row index=0>
        ra                dec                 z               delta       
     float64            float64            float64           float64      
------------------ ------------------ ----------------- ------------------
-34.90196644835447 -1.159330826846483 3.523275700157328 -1.503065938602433

In [18]:
corners.add_row(corner_data[corner_data['z']==max(corner_data['z'])][0])

In [19]:
corners

<Table length=2>
        ra                dec                 z                delta       
     float64            float64            float64            float64      
------------------ ------------------ ----------------- -------------------
-34.90196644835447 -1.159330826846483  3.08463316655781 -2.6700565094875603
-34.90196644835447 -1.159330826846483 3.523275700157328  -1.503065938602433

In [20]:
corner_data=deltas[deltas['ra']==quasars[1]['ra']] 

In [21]:
corners.add_row(corner_data[corner_data['z']==min(corner_data['z'])][0])

In [22]:
corners.add_row(corner_data[corner_data['z']==max(corner_data['z'])][0])

In [23]:
corners

<Table length=4>
         ra                 dec                 z                 delta       
      float64             float64            float64             float64      
------------------- ------------------- ------------------ -------------------
 -34.90196644835447  -1.159330826846483   3.08463316655781 -2.6700565094875603
 -34.90196644835447  -1.159330826846483  3.523275700157328  -1.503065938602433
-34.692674572422334 -1.0531637172445856 2.8041099376252516 0.24823932086580824
-34.692674572422334 -1.0531637172445856 3.3878630006634363  0.8335180931570678

In [24]:
corner_data=deltas[deltas['ra']==quasars[2]['ra']] 
corners.add_row(corner_data[corner_data['z']==min(corner_data['z'])][0])
corners.add_row(corner_data[corner_data['z']==max(corner_data['z'])][0])

In [25]:
corners

<Table length=6>
         ra                 dec                 z                 delta       
      float64             float64            float64             float64      
------------------- ------------------- ------------------ -------------------
 -34.90196644835447  -1.159330826846483   3.08463316655781 -2.6700565094875603
 -34.90196644835447  -1.159330826846483  3.523275700157328  -1.503065938602433
-34.692674572422334 -1.0531637172445856 2.8041099376252516 0.24823932086580824
-34.692674572422334 -1.0531637172445856 3.3878630006634363  0.8335180931570678
 -34.60865459248191 -0.8345530857219153  2.209615875200671 -0.7347692954871978
 -34.60865459248191 -0.8345530857219153 2.7029944354261946 -0.3120516786164653

In [26]:
corner_data=deltas[deltas['ra']==quasars[3]['ra']] 
corners.add_row(corner_data[corner_data['z']==min(corner_data['z'])][0])
corners.add_row(corner_data[corner_data['z']==max(corner_data['z'])][0])

In [27]:
corners

<Table length=8>
         ra                 dec                 z                 delta        
      float64             float64            float64             float64       
------------------- ------------------- ------------------ --------------------
 -34.90196644835447  -1.159330826846483   3.08463316655781  -2.6700565094875603
 -34.90196644835447  -1.159330826846483  3.523275700157328   -1.503065938602433
-34.692674572422334 -1.0531637172445856 2.8041099376252516  0.24823932086580824
-34.692674572422334 -1.0531637172445856 3.3878630006634363   0.8335180931570678
 -34.60865459248191 -0.8345530857219153  2.209615875200671  -0.7347692954871978
 -34.60865459248191 -0.8345530857219153 2.7029944354261946  -0.3120516786164653
-34.472523569472685 -0.9748963978803513 2.1692248999145027 -0.14715357314047095
-34.472523569472685 -0.9748963978803513 2.6555527855741072 -0.06717176539419378

In [28]:
corners['z'].name='redshift'

## Pass to x,y,z coordinates with comoving distance calculation for its own redshift

$$D_{c} = \frac{c}{H_{0}} \int_{0}^{z} (\Omega_{M}(1+z')^{3}+\Omega_{k}(1+z')^{2}+\Omega_{\Lambda})^{-1/2} \,dz' $$

In [29]:
#z to comoving
#voidfinder.distance.z_to_comoving_dist

Omega_M = 0.3147
c = const.c.to('km/s').value
def Distance(z,omega_m = Omega_M,h = 1):
    dist = np.ones(len(z))
    H0 = 100*h
    for i,redshift in enumerate(z):
        a_start = 1/(1+redshift)
        I = quad(f,a_start,1,args=omega_m)
        dist[i] = I[0]*(c/H0)
    return dist

def f(a,omega_m = Omega_M):
     return 1/(np.sqrt(a*omega_m*(1+((1-omega_m)*a**3/omega_m)))) 

In [30]:
corners['comoving']= Distance(corners['redshift'],Omega_M,1)

In [31]:
corners['comoving']

<Column name='comoving' dtype='float64' length=8>
 4441.089182834704
 4700.497500983059
 4252.891800657206
 4624.472891632714
3779.0382550917548
 4180.062188281467
 3742.353000373667
 4144.897513044186

In [32]:
#Another check for my point of interest at z=2.1
Distance([2.1],Omega_M,1)

array([3677.92839129])

In [41]:
#z to comoving
#voidfinder.distance.z_to_comoving_dist

Omega_M = 0.3147
c = const.c.to('km/s').value
def Distance(z,omega_m = Omega_M,h = 1):
    dist = np.ones(len(z))
    H0 = 100*h
    for i,redshift in enumerate(z):
        a_final=1+redshift
        I = quad(f,1,a_final,args=omega_m)
        dist[i] = I[0]*(c/H0)
    return dist

def f(a,omega_m = Omega_M):
     return 1/(np.sqrt(omega_m*(a**3)+(1-omega_m))) 

In [42]:
comoving_nesli= Distance(corners['redshift'],Omega_M,1)

In [43]:
comoving_nesli

array([4441.08918283, 4700.49750098, 4252.89180066, 4624.47289163,
       3779.03825509, 4180.06218828, 3742.35300037, 4144.89751304])

In [44]:
#Another check for my point of interest at z=2.1
Distance([2.1],Omega_M,1)

array([3677.92839129])

In [33]:
#voidfinder.ra_dec_to_xyz
ra = corners['ra']
dec = corners['dec']
comov = corners['comoving']

DtoR = np.pi/180.
ra_radian = ra*DtoR
dec_radian = dec*DtoR

x = comov*np.cos(ra_radian)*np.cos(dec_radian)
y = comov*np.sin(ra_radian)*np.cos(dec_radian)
z = comov*np.sin(dec_radian)

num_corners = x.shape[0]

coords_xyz = np.concatenate((x.reshape(num_corners,1),y.reshape(num_corners,1),z.reshape(num_corners,1)), axis=1)

In [44]:
coords_xyz=Table(coords_xyz,names=('x','y','z'))

In [49]:
from astropy.table import hstack
hstack([corners,coords_xyz])

<Table length=8>
         ra                 dec         ...         z         
      float64             float64       ...      float64      
------------------- ------------------- ... ------------------
 -34.90196644835447  -1.159330826846483 ... -89.85548875438052
 -34.90196644835447  -1.159330826846483 ... -95.10403483273109
-34.692674572422334 -1.0531637172445856 ... -78.16874405909016
-34.692674572422334 -1.0531637172445856 ... -84.99845630175138
 -34.60865459248191 -0.8345530857219153 ... -55.04238787559616
 -34.60865459248191 -0.8345530857219153 ... -60.88337528774644
-34.472523569472685 -0.9748963978803513 ... -63.67363265215281
-34.472523569472685 -0.9748963978803513 ...  -70.5226582313441

In [64]:
c = const.c.to('km/s').value
h=1
H0 = 100*h
dh=c/H0 

In [70]:
#My code from earlier
def integrand(x):
    return (Omega_M((1+x)**3)+1-Omega_M)**(-1/2)


#dc = dh* 
scipy.integrate.quad(integrand, 0, corners['redshift'][0])[0]


TypeError: 'float' object is not callable

## Return back to redshift and check

In [53]:
comov_calc= np.sqrt(x**2+y**2+z**2)

In [54]:
comov_calc

<Column name='comoving' dtype='float64' length=8>
 4441.089182834704
 4700.497500983059
 4252.891800657206
 4624.472891632714
3779.0382550917548
 4180.062188281467
 3742.353000373667
 4144.897513044187